behaviors:
    AIPlayer:
        trainer_type: ppo
        hyperparameters:
            batch_size: 2048 #4096
            buffer_size: 40960 #81920
            learning_rate: 0.0001
            beta: 0.005
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: linear
        network_settings:
            normalize: false
            hidden_units: 128 #256
            num_layers: 3 #4
            vis_encode_type: nature_cnn
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
        keep_checkpoints: 100
        max_steps: 80000000
        time_horizon: 256
        summary_freq: 30000